# This rule is not used by the project endpoint-monitoring-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to monitoring.licious.app resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: endpoint-monitoring-operator
    app.kubernetes.io/managed-by: kustomize
  name: endpointmonitor-viewer-role
rules:
- apiGroups:
  - monitoring.licious.app
  resources:
  - endpointmonitors
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - monitoring.licious.app
  resources:
  - endpointmonitors/status
  verbs:
  - get
