# This rule is not used by the project endpoint-monitoring-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over monitoring.licious.app.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: endpoint-monitoring-operator
    app.kubernetes.io/managed-by: kustomize
  name: endpointmonitor-admin-role
rules:
- apiGroups:
  - monitoring.licious.app
  resources:
  - endpointmonitors
  verbs:
  - '*'
- apiGroups:
  - monitoring.licious.app
  resources:
  - endpointmonitors/status
  verbs:
  - get
